/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:isar/isar.dart';

part 'sent_to_address.g.dart';

@Collection()
class SentToAddress {
  SentToAddress({
    required this.walletId,
    required this.txid,
    required this.value,
    this.label = "",
  });

  Id id = Isar.autoIncrement;

  @Index()
  late final String walletId;

  @Index(unique: true, composite: [CompositeIndex("walletId")])
  late final String txid;

  late final String value;

  late final String label;
}
