/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:convert';

import 'package:decimal/decimal.dart';

import '../util.dart';

class Amount {
  const Amount({required BigInt rawValue, required this.fractionDigits})
    : assert(fractionDigits >= 0),
      _value = rawValue;

  /// special zero case with [fractionDigits] set to 0
  static Amount get zero => .zeroWith(fractionDigits: 0);

  Amount.zeroWith({required int fractionDigits})
    : this(rawValue: BigInt.from(0), fractionDigits: fractionDigits);

  /// truncate decimal value to [fractionDigits] places
  Amount.fromDecimal(Decimal amount, {required int fractionDigits})
    : this(
        rawValue: amount.shift(fractionDigits).toBigInt(),
        fractionDigits: fractionDigits,
      );

  static String normalizeLocalizedNumber(
    String value, {
    required String locale,
  }) {
    final symbols = Util.getSymbolsFor(locale: locale);
    final groupSeparator = symbols?.GROUP_SEP ?? ",";
    final decimalSeparator = symbols?.DECIMAL_SEP ?? ".";

    if (groupSeparator == "." &&
        decimalSeparator != "." &&
        !value.contains(decimalSeparator)) {
      return RegExp(r'^[1-9]\d{0,2}(\.\d{3})+$').hasMatch(value)
          ? value.replaceAll(groupSeparator, "")
          : value;
    }

    return value
        .replaceAll(groupSeparator, "")
        .replaceFirst(decimalSeparator, ".");
  }

  static Decimal? tryParseLocalizedNumber(
    String value, {
    required String locale,
  }) {
    if (value.isEmpty || value.contains(RegExp(r'[+\-\x09-\x0D ]'))) {
      return null;
    }

    final symbols = Util.getSymbolsFor(locale: locale);
    final groupSeparator = symbols?.GROUP_SEP ?? ",";
    final decimalSeparator = symbols?.DECIMAL_SEP ?? ".";
    final escapedGroup = RegExp.escape(groupSeparator);
    final escapedDecimal = RegExp.escape(decimalSeparator);
    final integerPattern =
        r'(?:\d+|[1-9]\d{0,2}(?:' + escapedGroup + r'\d{3})+)';
    final localizedPattern = RegExp(
      '^(?:$integerPattern(?:$escapedDecimal\\d+)?|$escapedDecimal\\d+)\$',
    );

    // In locales that group digits with ".", a single-dot value with exactly
    // three trailing digits ("1.123") is both a validly grouped integer and a
    // plausible plain dot-decimal amount. Money input must not guess between
    // readings that differ 1000x, so such values are rejected outright.
    if (groupSeparator == "." &&
        decimalSeparator != "." &&
        !value.contains(decimalSeparator) &&
        RegExp(r'^[1-9]\d{0,2}\.\d{3}$').hasMatch(value)) {
      return null;
    }

    if (localizedPattern.hasMatch(value)) {
      return Decimal.tryParse(normalizeLocalizedNumber(value, locale: locale));
    }

    if (groupSeparator == "." &&
        decimalSeparator != "." &&
        !value.contains(decimalSeparator) &&
        RegExp(r'^(?:\d+(?:\.\d+)?|\.\d+)$').hasMatch(value)) {
      return Decimal.tryParse(value);
    }

    return null;
  }

  static Amount? tryParseFiatString(String value, {required String locale}) {
    if (value.isEmpty || value.contains(RegExp(r'[+\-\x09-\x0D ]'))) {
      return null;
    }

    // get number symbols for decimal place and group separator
    return Decimal.tryParse(
      normalizeLocalizedNumber(value, locale: locale),
    )?.toAmount(fractionDigits: 2);
  }

  // ===========================================================================
  // ======= Instance properties ===============================================

  final int fractionDigits;
  final BigInt _value;

  // ===========================================================================
  // ======= Getters ===========================================================

  /// raw base value
  BigInt get raw => _value;

  /// actual decimal vale represented
  Decimal get decimal => Decimal.fromBigInt(raw).shift(-1 * fractionDigits);

  /// convenience getter
  @Deprecated("provided for convenience only. Use fractionDigits instead.")
  int get decimals => fractionDigits;

  // ===========================================================================
  // ======= Serialization =====================================================

  Map<String, dynamic> toMap() {
    return {"raw": raw.toString(), "fractionDigits": fractionDigits};
  }

  String toJsonString() {
    return jsonEncode(toMap());
  }

  String fiatString({required String locale}) {
    final wholeNumber = decimal.truncate();

    // get number symbols for decimal place and group separator
    final numberSymbols = Util.getSymbolsFor(locale: locale);

    final String separator = numberSymbols?.DECIMAL_SEP ?? ".";

    final fraction = decimal - wholeNumber;

    String wholeNumberString = wholeNumber.toStringAsFixed(0);
    // insert group separator
    final regex = RegExp(r'\B(?=(\d{3})+(?!\d))');
    wholeNumberString = wholeNumberString.replaceAllMapped(
      regex,
      (m) => "${m.group(0)}${numberSymbols?.GROUP_SEP ?? ","}",
    );

    return "$wholeNumberString$separator${fraction.toStringAsFixed(2).substring(2)}";
  }
  // String localizedStringAsFixed({
  //   required String locale,
  //   int? decimalPlaces,
  // }) {
  //   decimalPlaces ??= fractionDigits;
  //   assert(decimalPlaces >= 0);
  //
  //   final wholeNumber = decimal.truncate();
  //
  //   if (decimalPlaces == 0) {
  //     return wholeNumber.toStringAsFixed(0);
  //   }
  //
  //   final String separator =
  //       (numberFormatSymbols[locale] as NumberSymbols?)?.DECIMAL_SEP ??
  //           (numberFormatSymbols[locale.substring(0, 2)] as NumberSymbols?)
  //               ?.DECIMAL_SEP ??
  //           ".";
  //
  //   final fraction = decimal - wholeNumber;
  //
  //   return "${wholeNumber.toStringAsFixed(0)}$separator${fraction.toStringAsFixed(decimalPlaces).substring(2)}";
  // }

  // ===========================================================================
  // ======= Deserialization ===================================================

  static Amount fromSerializedJsonString(String json) {
    final map = jsonDecode(json) as Map;
    return Amount(
      rawValue: BigInt.parse(map["raw"] as String),
      fractionDigits: map["fractionDigits"] as int,
    );
  }

  // ===========================================================================
  // ======= operators =========================================================

  bool operator >(Amount other) => decimal > other.decimal;

  bool operator <(Amount other) => decimal < other.decimal;

  bool operator >=(Amount other) => decimal >= other.decimal;

  bool operator <=(Amount other) => decimal <= other.decimal;

  Amount operator +(Amount other) {
    if (fractionDigits != other.fractionDigits) {
      throw ArgumentError(
        "fractionDigits do not match: this=$this, other=$other",
      );
    }
    return Amount(rawValue: raw + other.raw, fractionDigits: fractionDigits);
  }

  Amount operator -(Amount other) {
    if (fractionDigits != other.fractionDigits) {
      throw ArgumentError(
        "fractionDigits do not match: this=$this, other=$other",
      );
    }
    return Amount(rawValue: raw - other.raw, fractionDigits: fractionDigits);
  }

  Amount operator *(Amount other) {
    if (fractionDigits != other.fractionDigits) {
      throw ArgumentError(
        "fractionDigits do not match: this=$this, other=$other",
      );
    }
    return Amount(rawValue: raw * other.raw, fractionDigits: fractionDigits);
  }

  // ===========================================================================
  // ======= Overrides =========================================================

  @override
  String toString() => "Amount($raw, $fractionDigits)";

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Amount &&
          runtimeType == other.runtimeType &&
          raw == other.raw &&
          fractionDigits == other.fractionDigits;

  @override
  int get hashCode => Object.hashAll([raw, fractionDigits]);
}

// =============================================================================
// =============================================================================
// ======= Extensions ==========================================================

extension DecimalAmountExt on Decimal {
  Amount toAmount({required int fractionDigits}) {
    return Amount.fromDecimal(this, fractionDigits: fractionDigits);
  }
}

extension IntAmountExtension on int {
  Amount toAmountAsRaw({required int fractionDigits}) {
    return Amount(rawValue: BigInt.from(this), fractionDigits: fractionDigits);
  }
}
