
/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:stackwallet/pages_desktop_specific/desktop_home_view.dart';
import 'package:stackwallet/themes/stack_colors.dart';
import 'package:stackwallet/utilities/text_styles.dart';

class ExitToMyStackButton extends StatelessWidget {
  const ExitToMyStackButton({
    Key? key,
    this.onPressed,
  }) : super(key: key);

  final VoidCallback? onPressed;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(
        right: 24,
      ),
      child: SizedBox(
        height: 56,
        child: TextButton(
          style: Theme.of(context)
              .extension<StackColors>()!
              .getSmallSecondaryEnabledButtonStyle(context),
          onPressed: onPressed ??
              () {
                Navigator.of(context).popUntil(
                  ModalRoute.withName(DesktopHomeView.routeName),
                );
              },
          child: Padding(
            padding: const EdgeInsets.symmetric(
              horizontal: 30,
            ),
            child: Text(
              "Exit to My Stack",
              style: STextStyles.desktopButtonSmallSecondaryEnabled(context),
            ),
          ),
        ),
      ),
    );
  }
}
