/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import '../models/mwcmqs_server_model.dart';

abstract class DefaultMwcMqs {
  static const String defaultName = "Default";

  static List<MwcMqsServerModel> get all => [americas, asia, europe];
  static List<String> get defaultIds => ['americas', 'asia', 'europe'];

  static MwcMqsServerModel get americas => MwcMqsServerModel(
        host: 'MwcMqs.stackwallet.com',
        port: 443,
        name: 'Americas',
        id: 'americas',
        useSSL: true,
        enabled: true,
        isFailover: true,
        isDown: false,
      );

  static MwcMqsServerModel get asia => MwcMqsServerModel(
        host: 'MwcMqs.hyperbig.com',
        port: 443,
        name: 'Asia',
        id: 'asia',
        useSSL: true,
        enabled: true,
        isFailover: true,
        isDown: false,
      );

  static MwcMqsServerModel get europe => MwcMqsServerModel(
        host: 'MwcMqs.fastepic.eu',
        port: 443,
        name: 'Europe',
        id: 'europe',
        useSSL: true,
        enabled: true,
        isFailover: true,
        isDown: false,
      );

  static final defaultMwcMqsServer = americas;
}
