final Map<String, dynamic> darkJson = {
  "name": "Forest",
  "asset_bundle_url": "",
  "brightness": "light",
  "colors": {
    "coin": {
      "bitcoin": "0xFFFCC17B",
      "litecoin": "0xFF7FA6E1",
      "bitcoincash": "0xFF7BCFB8",
      "firo": "0xFFFF897A",
      "dogecoin": "0xFFFFE079",
      "epicCash": "0xFFC5C7CB",
      "ethereum": "0xFFA7ADE9",
      "monero": "0xFFFF9E6B",
      "namecoin": "0xFF91B1E1",
      "wownero": "0xFFED80C1",
      "particl": "0xFF8175BD"
    },
    "background": {
      "background": "0xFFF3FAF5",
      "backgroundAppBar": "0xFFF3FAF5"
    },
    "accent": {
      "blue": "0xFF077CBE",
      "green": "0xFF00A591",
      "yellow": "0xFFF4C517",
      "red": "0xFFD1382D",
      "orange": "0xFFFF985F",
      "dark": "0xFF22867A"
    },
    "text": {
      "dark_one": "0xFF232323",
      "dark_two": "0xFF333333",
      "dark_three": "0xFF696B6C",
      "white": "0xFFFFFFFF",
      "favorite": "0xFF232323",
      "error": "0xFF8D0006",
      "restore": "0xFF111215"
    },
    "button_text": {
      "primary": "0xFFFFFFFF",
      "secondary": "0xFF232323",
      "primary_disabled": "0xFFFFFFFF",
      "secondary_disabled": "0xFFBDD5DB",
      "border": "0xFFBDD5DB",
      "disabled": "0xFF22867A",
      "borderless": "0xFFFFFFFF",
      "borderless_disabled": "0xFF056EC6"
    },
    "switch": {
      "bg_on": "0xFF2DAB9C",
      "bg_off": "0xFFD6F0E8",
      "bg_disabled": "0xFFC5C6C9",
      "circle_on": "0xFFDEFFF2",
      "circle_off": "0xFFFBFCFF",
      "circle_disabled": "0xFFFBFCFF"
    },
    "button_back_colors": {
      "primary": "0xFF22867A",
      "secondary": "0xFFC2E2D5",
      "primary_disabled": "0xFFBDDBCB",
      "secondary_disabled": "0xFFBDBDBD",
      "border": "0xFF22867A",
      "border_disabled": "0xFFBDD5DB",
      "border_secondary": "0xFFC2E2D5",
      "border_secondary_disabled": "0xFFBDBDBD",
      "number": "0xFFFFFFFF",
      "numpad": "0xFF22867A",
      "nav": "0xFFFFFFFF",
    },
  },
  "overlay": "0xFF111215",
  "shadow": "0x0F2D3132",
  "text_subtitles": {
    "subtitle_one": "0xFF7E8284",
    "subtitle_two": "0xFF919393",
    "subtitle_three": "0xFFB0B2B2",
    "subtitle_four": "0xFFD1D3D3",
    "subtitle_five": "0xFFDEDFE1",
    "subtitle_six": "0xFFF1F1F1"
  },
  "number_text_default": "0xFFFFFFFF",
  "numpad_text_default": "0xFF22867A",
  "bottom_nav_text": "0xFFFFFFFF",
  "custom_text_button_enabled_text": "0xFF056EC6",
  "custom_text_button_disabled_text": "0xFF7E8284",
  "step_indicator": {
    "bg_check": "0xFFBBF0DB",
    "bg_number": "0xFFCDD9FF",
    "bg_inactive": "0xFFD2EDE5",
    "bg_lines": "0xFF90B8DC",
    "bg_lines_inactive": "0xFFBCEAD9",
    "icon_text": "0xFF22867A",
    "icon_number": "0xFF005BAF",
    "icon_inactive": "0xFFD4DFFF"
  },
  "checkbox": {
    "bg_checked": "0xFF22867A",
    "border_empty": "0xFF8C8F90",
    "bg_disabled": "0xFFB0C9ED",
    "icon_checked": "0xFFFFFFFF",
    "icon_disabled": "0xFFFFFFFF",
    "text_label": "0xFF232323"
  },
  "snack_bar": {
    "back_success": "0xFFADD6D2",
    "back_error": "0xFFADD6D2",
    "back_info": "0xFFCCD7FF",
    "text_success": "0xFF075547",
    "text_error": "0xFF8D0006",
    "text_info": "0xFF002569"
  },
  "icons": {
    "bottom_nav_icon_back": "0xFFA7C7CF",
    "bottom_nav_icon_icon": "0xFF22867A",
    "top_nav_icon_primary": "0xFF227386",
    "top_nav_icon_green": "0xFF00A591",
    "top_nav_icon_yellow": "0xFFFDD33A",
    "top_nav_icon_red": "0xFFEA4649",
    "settings_icon_back": "0xFFE0E3E3",
    "settings_icon_icon": "0xFF232323",
    "settings_icon_back_two": "0xFF80D2C8",
    "settings_icon_element": "0xFF00A591"
  },
  "text_field": {
    "active_bg": "0xFFE3FFF3",
    "default_bg": "0xFFDDF3EA",
    "error_bg": "0xFFF6C7C3",
    "success_bg": "0xFFADD6D2",
    "error_border": "0xFFF6C7C3",
    "success_border": "0xFFADD6D2",
    "active_search_icon_left": "0xFF86898C",
    "default_search_icon_left": "0xFF86898C",
    "error_search_icon_left": "0xFF8D0006",
    "success_search_icon_left": "0xFF006C4D",
    "active_text": "0xFF232323",
    "default_text": "0xFF86898C",
    "error_text": "0xFF000000",
    "success_text": "0xFF000000",
    "active_label": "0xFF86898C",
    "error_label": "0xFF8D0006",
    "success_label": "0xFF077C6E",
    "active_search_icon_right": "0xFF22867A",
    "default_search_icon_right": "0xFF22867A",
    "error_search_icon_right": "0xFF8D0006",
    "success_search_icon_right": "0xFF077C6E"
  },
  "settings_item_level_two": {
    "active_bg": "0xFFFFFFFF",
    "active_text": "0xFF232323",
    "active_sub": "0xFF8C8F90"
  },
  "radio_button": {
    "icon_border": "0xFF056EC6",
    "icon_border_disabled": "0xFF8C8D97",
    "border_enabled": "0xFF056EC6",
    "border_disabled": "0xFF8C8D97",
    "icon_circle": "0xFF056EC6",
    "icon_enabled": "0xFF056EC6",
    "text_enabled": "0xFF42444B",
    "text_disabled": "0xFF42444B",
    "label_enabled": "0xFF8C8F90",
    "label_disabled": "0xFF8C8F90"
  },
  "info_text": {
    "item_bg": "0xFFFFFFFF",
    "item_label": "0xFF838788",
    "item_text": "0xFF232323",
    "item_icons": "0xFF056EC6"
  },
  "popup_bg": "0xFFFFFFFF",
  "currency_list_item_bg": "0xFFF0F5F7",
  "bottom_nav": {
    "sw_bg": "0xFFFFFFFF",
    "sw_mid": "0xFFFFFFFF",
    "sw_bottom": "0xFF232323",
    "shadow": "0xFF388192",
    "splash": "0xFF8E9192",
    "highlight": "0xFFA9ACAC",
    "warning_foreground": "0xFF232323",
    "warning_background": "0xFFF6C7C3",
    "loading_overlay_text_color": "0xFFF7F7F7",
    "my_stack_contact_icon_bg": "0xFFD8E7EB",
    "text_confirm_total_amount": "0xFF232323",
    "text_selected_word_table_iterm": "0xFF232323"
  },
  "favorite_star": {"active": "0xFFF4C517", "inactive": "0xFFB0B2B2"},
  "rate_type_toggle": {
    "color_on": "0xFFDDF3EA",
    "color_off": "0xFFFFFFFF",
    "desktop_color_on": "0xFFDDF3EA",
    "desktop_color_off": "0xFFC2E2D5"
  },
  "token_view": {
    "eth_tag_text": "0xFFFFFFFF",
    "eth_tag_bg": "0xFF4D5798",
    "eth_wallet_tag_text": "0xFF4D5798",
    "eth_wallet_tag_bg": "0xFFF0F3FD",
    "token_summary_text_primary": "0xFF232323",
    "token_summary_text_secondary": "0xFF8488AB",
    "token_summary_bg": "0xFFE9EAFF",
    "token_summary_button_bg": "0xFFFFFFFF",
    "token_summary_icon": "0xFF424A97"
  },
  "box_shadows": {
    "standard": {
      "color": "0x0F2D3132",
      "spread_radius": 3.0,
      "blur_radius": 4.0
    },
    "home_view_button_bar": {
      "color": "0x0F2D3132",
      "spread_radius": 3.0,
      "blur_radius": 4.0
    }
  },
  "assets": {
    "background": "",
    "bitcoin": "svg/coin_icons/small/Bitcoin.svg",
    "litecoin": "svg/coin_icons/small/Litecoin.svg",
    "bitcoincash": "svg/coin_icons/small/Bitcoincash.svg",
    "dogecoin": "svg/coin_icons/small/Dogecoin.svg",
    "epicCash": "svg/coin_icons/small/EpicCash.svg",
    "ethereum": "svg/coin_icons/small/Ethereum.svg",
    "firo": "svg/coin_icons/small/Firo.svg",
    "monero": "svg/coin_icons/small/Monero.svg",
    "wownero": "svg/coin_icons/small/Wownero.svg",
    "namecoin": "svg/coin_icons/small/Namecoin.svg",
    "particl": "svg/coin_icons/small/Particl.svg",
    "bitcoin_image": "svg/coin_icons/big/bitcoin.svg",
    "litecoin_image": "svg/coin_icons/big/litecoin.svg",
    "bitcoincash_image": "svg/coin_icons/big/bitcoincash.svg",
    "dogecoin_image": "svg/coin_icons/big/doge.svg",
    "epicCash_image": "svg/coin_icons/big/epic-cash.svg",
    "ethereum_image": "svg/coin_icons/big/ethereum.svg",
    "firo_image": "svg/coin_icons/big/firo.svg",
    "monero_image": "svg/coin_icons/big/monero.svg",
    "wownero_image": "svg/coin_icons/big/wownero.svg",
    "namecoin_image": "svg/coin_icons/big/namecoin.svg",
    "particl_image": "svg/coin_icons/big/particl.svg",
    "bell_new": "svg/bell-new.svg",
    "persona_incognito": "svg/persona-incognito-1.svg",
    "persona_easy": "svg/persona-easy-1.svg",
    "stack": "svg/stack.svg",
    "stack_icon": "svg/stack-icon1.svg",
    "receive": "svg/tx-icon-receive.svg",
    "receive_pending": "svg/tx-icon-receive-pending.svg",
    "receive_cancelled": "svg/tx-icon-receive-failed.svg",
    "send": "svg/tx-icon-send.svg",
    "send_pending": "svg/tx-icon-send-pending.svg",
    "send_cancelled": "svg/tx-icon-send-failed.svg",
    "theme_preview": "svg/forest-theme.svg",
  }
};
