/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';

import '../../../../../themes/stack_colors.dart';
import '../../../../../utilities/text_styles.dart';
import '../../../../../utilities/util.dart';
import '../../../../../wallets/crypto_currency/crypto_currency.dart';
import '../../../../../wallets/crypto_currency/intermediate/cryptonote_currency.dart';
import '../../../../../widgets/desktop/desktop_dialog.dart';
import '../../../../../widgets/desktop/desktop_dialog_close_button.dart';
import '../../../../../widgets/desktop/primary_button.dart';
import '../../../../../widgets/desktop/secondary_button.dart';
import '../../../../../widgets/stack_dialog.dart';
import '../../../../../widgets/start_height_picker.dart';

class ConfirmFullRescanDialog extends StatefulWidget {
  const ConfirmFullRescanDialog({
    super.key,
    required this.coin,
    required this.onConfirm,
  });

  final CryptoCurrency coin;
  final void Function(int height) onConfirm;

  @override
  State<ConfirmFullRescanDialog> createState() =>
      _ConfirmFullRescanDialogState();
}

class _ConfirmFullRescanDialogState extends State<ConfirmFullRescanDialog> {
  late final StartHeightPickerController _heightController;

  @override
  void initState() {
    super.initState();
    _heightController = StartHeightPickerController();
  }

  @override
  void dispose() {
    _heightController.dispose();
    super.dispose();
  }

  bool get _showHeightPicker =>
      widget.coin is CryptonoteCurrency ||
      widget.coin is Epiccash ||
      widget.coin is Mimblewimblecoin;

  int get _selectedHeight => _showHeightPicker ? _heightController.height : 0;

  @override
  Widget build(BuildContext context) {
    if (Util.isDesktop) {
      return DesktopDialog(
        maxWidth: 576,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Padding(
                  padding: const EdgeInsets.only(left: 32),
                  child: Text(
                    "Rescan blockchain",
                    style: STextStyles.desktopH3(context),
                  ),
                ),
                const DesktopDialogCloseButton(),
              ],
            ),
            Padding(
              padding: const EdgeInsets.only(
                top: 8,
                left: 32,
                right: 32,
                bottom: 32,
              ),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(
                    "Warning! It may take a while. If you exit before completion, you will have to redo the process.",
                    style: STextStyles.desktopTextSmall(context),
                  ),
                  if (_showHeightPicker) ...[
                    const SizedBox(height: 24),
                    StartHeightPicker(
                      coin: widget.coin,
                      controller: _heightController,
                    ),
                  ],
                  const SizedBox(height: 43),
                  Row(
                    children: [
                      Expanded(
                        child: SecondaryButton(
                          buttonHeight: ButtonHeight.l,
                          onPressed: Navigator.of(context).pop,
                          label: "Cancel",
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: PrimaryButton(
                          buttonHeight: ButtonHeight.l,
                          onPressed: () {
                            Navigator.of(context).pop();
                            widget.onConfirm(_selectedHeight);
                          },
                          label: "Rescan",
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      );
    } else {
      return WillPopScope(
        onWillPop: () async {
          return true;
        },
        child: StackDialogBase(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SelectableText(
                "Rescan blockchain",
                style: STextStyles.pageTitleH2(context),
              ),
              const SizedBox(height: 8),
              SelectableText(
                "Warning! It may take a while. If you exit before completion, you will have to redo the process.",
                style: STextStyles.smallMed14(context),
              ),
              if (_showHeightPicker) ...[
                const SizedBox(height: 16),
                StartHeightPicker(
                  coin: widget.coin,
                  controller: _heightController,
                ),
              ],
              const SizedBox(height: 20),
              Row(
                children: [
                  Expanded(
                    child: TextButton(
                      style: Theme.of(context)
                          .extension<StackColors>()!
                          .getSecondaryEnabledButtonStyle(context),
                      child: Text(
                        "Cancel",
                        style: STextStyles.itemSubtitle12(context),
                      ),
                      onPressed: () {
                        Navigator.of(context).pop();
                      },
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: TextButton(
                      style: Theme.of(context)
                          .extension<StackColors>()!
                          .getPrimaryEnabledButtonStyle(context),
                      child: Text("Rescan", style: STextStyles.button(context)),
                      onPressed: () {
                        Navigator.of(context).pop();
                        widget.onConfirm(_selectedHeight);
                      },
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      );
    }
  }
}
